# Generated by Django 5.1 on 2024-10-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
